import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/context/AuthProvider";
import {Toaster} from "@/components/ui/sonner";
import Footer from "@/components/Footer";
import React from "react";
import {ThemeProvider} from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <AuthProvider>
          <html lang="en">
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <ThemeProvider
          attribute="class"
          defaultTheme="default"
          enableSystem={true}
          disableTransitionOnChange={true}
          >

              {children}
              <Footer />
              <Toaster/>
          </ThemeProvider>

          </body>
          </html>
      </AuthProvider>

  );
}
